apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vllm-hyperdisk
provisioner: pd.csi.storage.gke.io
parameters:
  type: hyperdisk-balanced
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-output-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vllm-hyperdisk
  resources:
    requests:
      storage: 50Gi